[project]
authors = ["Joseph Kuo <jovesus@gmail.com>"]
channels = ["conda-forge"]
name = "AnnoFig"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
dash = ">=2.18.2,<3"
dash-bootstrap-components = ">=1.7.1,<2"
pandas = ">=2.2.3,<3"
plotly = ">=6.0.0,<7"
matplotlib = ">=3.10.1,<4"
seaborn = ">=0.13.2,<0.14"
dash-daq = ">=0.5.0,<0.6"
